//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolany.Ice.Ai.DolanyAI.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class 日志
    {
        public long ID { get; set; }
        public string 时间 { get; set; }
        public string 来源 { get; set; }
        public string 类型 { get; set; }
        public string 内容 { get; set; }
        public string 颜色 { get; set; }
    }
}
