//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolany.IWS2000.Ai.DolanyAI.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgSendCache
    {
        public string Id { get; set; }
        public long Aim { get; set; }
        public int Type { get; set; }
        public string Msg { get; set; }
        public string Guid { get; set; }
        public int SerialNum { get; set; }
    }
}
