//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolany.Ai.MQ.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgCommand
    {
        public string Id { get; set; }
        public string Msg { get; set; }
        public System.DateTime Time { get; set; }
        public string Command { get; set; }
        public long ToQQ { get; set; }
        public long ToGroup { get; set; }
        public long AiNum { get; set; }
    }
}
