<?xml version="1.0" encoding="utf-8"?><Database Name="Db" Class="CartoonSayingsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\AI\CartoonSaying\Db.mdf;Integrated Security=True" SettingsObjectName="AILib.Properties.Settings" SettingsPropertyName="DbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cartoon" Member="Cartoon">
    <Type Name="Cartoon">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sayings" Member="Sayings">
    <Type Name="Sayings">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Saying" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CharactorId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Charactor" Member="Charactor">
    <Type Name="Charactor">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CartoonId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Syonoym" Member="Syonoym">
    <Type Name="Syonoym">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Word1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Word2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>