//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolany.Ai.Reborn.DolanyAI.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishItem
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int RareRate { get; set; }
        public string Icon { get; set; }
    }
}
