//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolany.QQAI.Plugins.DolanyAI.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepeaterAvailable
    {
        public string Id { get; set; }
        public long GroupNumber { get; set; }
        public bool Available { get; set; }
    }
}
