<?xml version="1.0" encoding="utf-8"?><Database Name="AIDb" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Db\AIDb.mdf;Integrated Security=True" SettingsObjectName="AILib.Properties.Settings" SettingsPropertyName="AIDbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Table">
    <Type Name="Table">
      <Column Name="GroupNumber" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Creator" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Available" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>